body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Описание идеи
        Опишите вашу идею, как можно более подробно, с примерами, референсами и другой полезной информацией.

  - type: textarea
    attributes:
      label: "Какие проблемы вы хотите решить?"
      description: "Опишите конкретные проблемы, с которыми вы сталкиваетесь и которые эта идея должна решить."

  - type: textarea
    attributes:
      label: "Подробное описание"
      description: "Опишите идею подробно. Добавьте ссылки на референсы, если можно."

  - type: textarea
    id: improvements
    attributes:
      label: "Весомые причины для того, чтобы коллектив взял эту идею в работу"
      description: "От того, как удачно вы опишете этот пункт, зависит, насколько быстро и легко задача будет рассмотрена и взята в работу."

  - type: checkboxes
    attributes:
      label: "Проверка"
      options:
        - label: "Я проверил(а), что подобная идея ещё не предлагалась."
        - label: "Я готов(а) внести вклад в реализацию этой идеи."
