name: "[Идея] "
description: "Опишите вашу идею"
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Описание идеи
        Опишите вашу идею, как можно более подробно, с примерами, референсами и другой полезной информацией.

  - type: textarea
    attributes:
      label: "Какие проблемы вы хотите решить?"
      description: "Опишите конкретные проблемы, с которыми вы сталкиваетесь и которые эта идея должна решить."
      placeholder: "Опишите проблемы здесь..."

  - type: textarea
    attributes:
      label: "Подробное описание"
      description: "Опишите идею подробно. Добавьте ссылки на референсы, если можно."
      placeholder: "Опишите вашу идею..."

  - type: textarea
    id: improvements
    attributes:
      label: "Топ-3 улучшения, которые принесет эта идея"
      description: "Перечислите три главных улучшения, которые будут достигнуты благодаря реализации этой идеи."
      value: |
        1.
        2.
        3.

  - type: checkboxes
    attributes:
      label: "Проверка"
      options:
        - label: "Я проверил(а), что подобная идея ещё не предлагалась."
        - label: "Я готов(а) внести вклад в реализацию этой идеи."
